#cloud-config
package_update: true
package_upgrade: true

write_files:
  - path: /etc/systemd/system/github-runner.service
    permissions: '0644'
    content: |
      [Unit]
      Description=GitHub Actions Runner
      After=network.target

      [Service]
      ExecStart=/actions-runner/run.sh
      WorkingDirectory=/actions-runner
      Restart=always
      StartLimitInterval=0

      [Install]
      WantedBy=multi-user.target

runcmd:
  # 1. Install dependencies
  - apt-get update && apt-get install -y curl jq git azure-cli auditd

  # 2. Login to Azure using UAMI
  - az login --identity --client-id 3d05dcf4-74af-499d-9afa-6600de55713e

  # 3. Fetch GitHub PAT from Azure Key Vault
  - export PAT=$(az keyvault secret show \
      --vault-name kv-dati-ghrunner \
      --name github-pat \
      --query value -o tsv)

  # 4. Set up GitHub Actions runner
  - mkdir -p /actions-runner && cd /actions-runner
  - curl -o actions-runner-linux-x64.tar.gz -L https://github.com/actions/runner/releases/download/v2.311.0/actions-runner-linux-x64-2.311.0.tar.gz
  - tar xzf actions-runner-linux-x64.tar.gz
  - ./bin/installdependencies.sh
  - ./config.sh --url https://github.com/Yogesh3052/azure-oidc-vmss-runners-poc --token $PAT --unattended --labels vmss,linux

  # 5. Enable systemd service for GitHub runner
  - systemctl daemon-reexec
  - systemctl daemon-reload
  - systemctl enable github-runner
  - systemctl start github-runner

  # 6. Enable Linux auditd (session logging)
  - systemctl enable auditd
  - systemctl start auditd
