#cloud-config
package_update: true
package_upgrade: true

write_files:
  - path: /var/log/runner-debug.log
    content: |
      [runner-debug-log initialized]

runcmd:
  # Create a folder
  - mkdir actions-runner && cd actions-runner
  # Download the latest runner package
  - curl -o actions-runner-linux-x64-2.326.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.326.0/actions-runner-linux-x64-2.326.0.tar.gz
  # Optional: Validate the hash
  - echo "9c74af9b4352bbc99aecc7353b47bcdfcd1b2a0f6d15af54a99f54a0c14a1de8  actions-runner-linux-x64-2.326.0.tar.gz" | shasum -a 256 -c
  # Extract the installer
  - tar xzf ./actions-runner-linux-x64-2.326.0.tar.gz

  - PAT=$(az keyvault secret show --vault-name kv-dati-ghrunner --name github-pat --query "value" -o tsv)
  # Create the runner and start the configuration experience
  - ./config.sh --url https://github.com/Yogesh3052/azure-oidc-vmss-runners-poc --token "$PAT" --ephemeral --name $(hostname) --labels "vmss,oidc" --replace
  # Install the runner service
  - ./run.sh
  